language: erlang
notifications:
  recipients:
    - brett.kochendorfer@gmail.com
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make compile
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"  
